spring:
  data:
    mongodb:
      port: 0 # when flapdoodle using
      database: db

  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false

    command:
      version:
        enabled: false

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  #  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local