spring:
  data:
    mongodb:
      port: 0 # when flapdoodle using
      database: db
  mongodb:
    embedded:
      version: 3.4.0
  profiles:
    default: local-dev
  main:
    web-application-type: reactive

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local