spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: never

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

    show-sql: false

  shell:
    interactive:
      enabled: true

  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql


logging:
  level:
    ROOT: ERROR