create table author (
    author_id bigint generated by default as identity,
    full_name varchar(255),
    CONSTRAINT PK_AUTHOR_AUTHOR_ID PRIMARY KEY (author_id)
);

create table book (
    book_id bigint generated by default as identity,
    author_id bigint not null,
    title varchar(255),
    CONSTRAINT PK_BOOK_BOOK_ID PRIMARY KEY (book_id)
);

create table book_comment (
    book_comment_id bigint generated by default as identity,
    book_id bigint not null,
    text varchar(1000),
    CONSTRAINT PK_BOOK_COMMENT_BOOK_COMMENT_ID PRIMARY KEY (book_comment_id)
);

create table book_genre (
    book_id bigint not null,
    genre_id bigint not null
);

create table genre (
    genre_id bigint generated by default as identity,
    name varchar(255),
    CONSTRAINT PK_GENRE_GENRE_ID PRIMARY KEY (genre_id)
);

create index IND_BOOK_AUTHOR_ID
   on book (author_id);
create index IND_BOOK_COMMENT_BOOK_ID
   on book_comment (book_id);
create index IND_BOOK_GENRE_BOOK_ID
   on book_genre (book_id);

alter table if exists book
   add constraint FK_BOOK_AUTHOR_ID
   foreign key (author_id)
   references author;

alter table if exists book_comment
   add constraint FK_BOOK_COMMENT_BOOK_ID FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID) ON DELETE CASCADE;

alter table if exists book_genre
   add constraint FK_BOOK_GENRE_GENRE_ID
   foreign key (genre_id)
   references genre;

alter table if exists book_genre
   add constraint FK_BOOK_GENRE_BOOK_ID
   foreign key (book_id)
   references book;